### ISSUE TITLE
建议官方帖个标准的my.cnf的配置

### ISSUE THREAD

**Issue by DarkiT** [alibaba/AliSQL#10]
建议官方帖个标准的my.cnf的配置，wiki里面的配置太高端了一般中小企业不会用那么高大上的服务器。

**Comment by Tanged** [comment]
这个好，建议提供一份通用的优化配置及建议。谢谢！

**Comment by Tanged** [comment]
这个好，建议提供一份通用的优化配置（以及配置建议）。谢谢！

**Comment by Xiphin** [comment]
非常需要

**Comment by xpchild** [comment]
https://github.com/alibaba/AliSQL/wiki 
wiki中提供了三种规格的my.cnf [small, middle, large] 做参考。

**Comment by JeremieAstray** [comment]
i need it!

**Comment by JakeXu** [comment]
建议对于my.cnf [small, middle, large] 各自配置是否标注下适用的服务器配置
