### ISSUE TITLE
配置参数错误，按照8c-16.cnf

### ISSUE THREAD

**Issue by shitian1** [alibaba/AliSQL#11]
2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_rds-anonymous-in-gtid-out-enable=1'
522 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_tokudb_cache_size=13108M'
523 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_opt_rds_enable_set_default_engine=OFF'
524 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_innodb_rds_autoinc_persistent_interval=1'
525 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_implicit_primary_key=1'
526 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_tokudb_checkpointing_period=60'
527 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_thread_pool_stall_limit=30'
528 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_thread_pool_oversubscribe=10'
529 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_max_statement_time=0'
530 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_tokudb_commit_sync=ON'
531 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_tokudb_support_xa=ON'
532 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_rds_set_connection_id_enabled=ON'
533 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_innodb_rds_log_checksum_algorithm=INNODB'
534 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_rds_check_core_file_enabled=ON'
535 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_tokudb_rpl_lookup_rows=OFF'
536 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_tokudb_fs_reserve_percent=5'
537 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_tokudb_buffer_pool_ratio=0'
538 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_innodb_rds_autoinc_persistent=ON'
539 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_rds_enable_log_global_var_update=ON'
540 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_opt_rds_last_error_gtid=ON'
541 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_tokudb_rpl_unique_checks=OFF'
542 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_tokudb_directio=OFF'
543 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_tokudb_fsync_log_period=0'
544 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_tokudb_row_format=tokudb_zlib'
545 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_rds_expand_fast_index_creation=ON'
546 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_rds_slave_read_no_lock=ON'
547 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_rpl_semi_sync_slave_trace_level=1'
548 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_rpl_semi_sync_master_timeout=1000'
549 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_rpl_semi_sync_master_trace_level=1'
550 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_rpl_semi_sync_slave_enabled=OFF'
551 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_rpl_semi_sync_master_enabled=OFF'
552 2016-10-16 01:21:07 17103 [Warning] /opt/local/mysql/bin/mysqld: unknown variable 'loose_rpl_semi_sync_master_wait_no_slave=ON'

**Comment by xpchild** [comment]
这些参数是随后即将要放出来的功能所对应的配置， 目前有loose前缀，只会有warning信息，不会是错误。

**Comment by elsery** [comment]
只是警告 应该没多少大问题
