### ISSUE TITLE
太令人遗憾了，AliSQL社区版已经4年没有更新维护了，我们做了一款MySQL HTAP数据库，大家来看看吧

### ISSUE THREAD

**Issue by OpenDataBase** [alibaba/AliSQL#112]
非常遗憾，自从2018年5月之后，AliSQL就再也没有维护过开源版本了，嘛，这也无可厚非，开不开源是人家自己的决定，不过，中国MySQL开源生态的大旗，还是得有人得扛起来。

我们现在做了一款基于MySQL内核的HTAP数据库，对标Heatwave架构，未来会支持分布式、云原生等架构，欢迎对数据库感兴趣的朋友们一起来共建：https://github.com/stoneatom/stonedb

我们的2.0架构应该是业内比较先进的一波，也和阿里的一些闭源数据库产品有着相似的理念，不过我们是完完全全、彻彻底底的长期开源，目前架构设计文档已经在Github上公布，欢迎大家了解：https://github.com/stoneatom/stonedb/issues/436

**Comment by yubinr** [comment]
https://github.com/ApsaraDB/galaxyengine

**Comment by wkgcass** [comment]
KPI开源是这样的

**Comment by hustjieke** [comment]
> 非常遗憾，自从2018年5月之后，AliSQL就再也没有维护过开源版本了，嘛，这也无可厚非，开不开源是人家自己的决定，不过，中国MySQL开源生态的大旗，还是得有人得扛起来。
> 
> 我们现在做了一款基于MySQL内核的HTAP数据库，对标Heatwave架构，未来会支持分布式、云原生等架构，欢迎对数据库感兴趣的朋友们一起来共建：https://github.com/stoneatom/stonedb
> 
> 我们是完完全全、彻彻底底的长期开源，目前架构设计文档已经在Github上公布，欢迎大家了解~

这哥们虽然不知道是谁，不要这么黑我们 StoneDB，我们做开源，但不会砸别人场，如果有什么利益冲突，请到我们自己社区提 issue 给我们意见，不要通过这种方式黑我们，谢谢！

**Comment by leonardBang** [comment]
> 非常遗憾，自从2018年5月之后，AliSQL就再也没有维护过开源版本了，嘛，这也无可厚非，开不开源是人家自己的决定，不过，中国MySQL开源生态的大旗，还是得有人得扛起来。
> 
> 我们现在做了一款基于MySQL内核的HTAP数据库，对标Heatwave架构，未来会支持分布式、云原生等架构，欢迎对数据库感兴趣的朋友们一起来共建：https://github.com/stoneatom/stonedb
> 
> 我们是完完全全、彻彻底底的长期开源，目前架构设计文档已经在Github上公布，欢迎大家了解~


看到这么多人点灭我就放心了，每个开源社区/产品都有其生命周期，或因为商业公司的策略，或因为开源社区自身的原因，活不下来的开源项目一大堆，实在没必要阴阳怪气地踩低别人来抬高自己。另外以我浅薄的认知，”中国MySQL开源生态的大旗“ 能抗的公司和产品还是挺多的, 阿里，腾讯都有蛮多优秀的数据库人才，贵司老板也曾是其中一员，TiDB, OceanbBase 这类开源产品都挺不错的， 这面大旗还真不一定需要你们抗。

攘攘为利，实在没有必要打着拯救中国MySQL开源生态的大旗，踩着KPI开源&阿里两大热点IP，干着推广你们的开源项目的勾当。你们开源社区策略真要这么玩，大家也理解：赚钱嘛，不寒碜。

**Comment by xpchild** [comment]
感谢大家的关心， AliSQL 开源的这个版本是基于 MySQL 5.6 的版本， 因为版本兼容和官方 8.0 的推出，以及关联阿里云产品和客户生态的种种历史，阿里开源的 MySQL 8.0 版本在这里：

https://github.com/ApsaraDB/galaxyengine

对于 8.0 版本，我们做了非常大的改进：

1. 全新的分布式事务系统，支持分布式事务和全局一致性
2. X-protocol 交互协议，支持RPC协议替换JDBC
3. X-Engine 引擎
4. X-Paxos 协议，实现数据零丢失并持续可用
5. 大量的企业级功能(Sequence engine, Recycle Bin, CCL, 监控等等)

对于开源，我们是诚意满满的，这些功能是支持 PolarDB-X 分布式数据库的核心功能，我们毫无保留进行了开源。

详细参考下：https://developer.aliyun.com/article/795058?spm=a2c6h.12873639.article-detail.68.d3ba4c1eBDaODZ

对于 5.6 的版本：1. 官方已经停止维护  2. 大量客户还在 5.6 版本上使用 3. 历史原因导致 8.0 没有在同一个repo上。
导致我们没有在 5.6上做更新，但又不能关闭。

但开源我们一直没有停止过。

**Comment by leonardBang** [comment]
> > 看到这么多人点灭我就放心了，每个开源社区/产品都有其生命周期，或因为商业公司的策略，或因为开源社区自身的原因，活不下来的开源项目一大堆，实在没必要阴阳怪气地踩低别人来抬高自己。另外以我浅薄的认知，”中国MySQL开源生态的大旗“ 能扛的公司和产品还是挺多的, 阿里，腾讯都有蛮多优秀的数据库人才，贵司老板也曾是其中一员，TiDB, OceanbBase 这类开源产品都挺不错的， 这面大旗还真不一定需要你们扛。
> > 攘攘为利，实在没有必要打着拯救中国MySQL开源生态的大旗，踩着KPI开源&阿里两大热点IP，干着推广你们的开源项目的勾当。你们开源社区策略真要这么玩，大家也理解：赚钱嘛，不寒碜。
> 
> 你还真是会拱火啊。我来吐槽AliSQL，你扯上其他厂商干什么？

你不是来吐槽AliSQL的，你是来推广你的开源产品

> 我们在讨论AliSQL的开源死亡，你非得把我的话语带到群体AOE？你真行啊，

不是”我们在讨论“，就你一个人发起了这个标题党issue

> 扯上其他开源厂商就能替 AliSQL 的 KPI 虚假开源平反么？不正是打了 ALiSQL 的脸？

AliSQL 的开源是不是KPI我不清楚，我也没用过这个开源项目。我只是看不惯你这种踩人上位的方式，打不打脸下面有AliSQL的人在回复，我目前看到的都是点赞，我粗浅地理解你没有打脸成功

> 我尊重任何一家技术公司的员工，但我劝你不要因为在某个公司工作，就彻底把自己搞魔怔了，AliSQL 的开源停止维护整整 4 年连个官方说明都不肯出，你觉得这是负责任的表现？

没看出你什么地方尊重了，我并不在数据库团队，专注的领域和数据库关系不大，让你失望了，也没用过AliSQL，我甚至都没有关注这个项目。这个项目四年没更新，是你这个”资深社区用户“突然良心发现来这个项目下指点江山，还是直接奔着推广你们开源项目而来，这个issue是你在当前开源组织下开的第一个issue哟，这说明了啥？读者自有评价。

**Comment by jackwener** [comment]
世界上没有一直维护下去开源项目属实非常多
贵司的运营人员确实很累，每个项目你们都要去回复，不得累坏啊。

我还可以给个建议，为了出海，可以去RethinkDB等项目里回复一下
Apache里有很多项目接近 retire 的，都可以回复

把他们都骂一通👍骂醒他们！

**Comment by leonardBang** [comment]
> 世界上没有一直维护下去开源项目属实非常多 贵司的运营人员确实很累，每个项目你们都要去回复，不得累坏啊。
> 
> 我还可以给个建议，为了出海，可以去RethinkDB等项目里回复一下 Apache里有很多项目接近 retire 的，都可以回复
> 
> 把他们都骂一通👍骂醒他们！

Big +1 🐶

**Comment by Xuanwo** [comment]
三十年河东三十年河西，莫欺项目凉。

---

> 本 Issue 已经 Archive 到 https://archive.ph/wip/7T0ih
>
> 等 StoneDB 也凉了 *(想必是不会的，毕竟要长期开源)* 的时候希望有人能一样骂醒。

**Comment by Xuanwo** [comment]
项目总是有生命周期的，开源项目尤其如此。

这个 Issue 的价值是确实指出了 AliSQL 维护已经停滞的情况，为了避免类似的问题再度出现，我建议维护者 @xpchild

- 在 README 中明确说明当前项目的状态，给出替代或迁移方案
- 关闭已有的重复 Issue，给予官方回复
- 必要的时候将该项目设置为 Archive

从另一个角度看，阿里的开源治理很多工作需要去做，比如：

- 项目退出机制：已经不再维护的项目需要有退出通道
- 项目持续维护：如上面评论吐槽的，项目开源之后没有持续维护，在对应的业务部门调整后，项目往往就停滞了。从 Apache Way 的角度来看，就是阿里开源出来的很多项目都缺乏社区多样性，只有开源项目却没有对应的开源社区。
- 项目开源治理：很多项目都以 Source Available 方式提供的，Issues / PR 流程都不开放，社区很难参与进去

这些都不是一朝一夕的事情，企业内要转变观念，调整开源项目的考核机制，开源社区的参与者也要一同来改进相关的流程。但是像这个 Issue 这样踩一捧一大可不必，踏踏实实做自己的项目，为社区共同体创造价值，自然会获得大家的尊重。

**Comment by Zheaoli** [comment]
抗大旗之前先学会做人做事，没事就跑出来拉扯一下博一下眼球，可能也只能在 CSDN 的报道中扛起xx的大旗了

**Comment by Xuanwo** [comment]
> * 在 README 中明确说明当前项目的状态，给出替代或迁移方案

关于这一点，我提交了 PR https://github.com/alibaba/AliSQL/pull/113，请 @xpchild Review

**Comment by Zheaoli** [comment]
> 我从来没博眼球，个人也没有在除Github以外的任何平台传播过，我不知道是谁要来一个closed的issue下面到处发表圣人锐评，博眼球的到底是谁？
> 
> 你没有资格去评判一个个体不会做人做事，我怼的也从来不是任何一个ALiSQL的同学，你要是真不懂，我建议你可以和楼上的Databend的漩涡同学多学习，讽刺完我还能热心地给ALiSQL提点儿有用的建议，而不是像你这般一上来先人身攻击。


好耶，现在倒是开始战术转进了，当时“嘛，这也无可厚非，开不开源是人家自己的决定，不过，中国MySQL开源生态的大旗，还是得有人得扛起来。”的意气风发呢

> 你没有资格去评判一个个体不会做人做事

的确，我好像也没啥资格去指责说你这个人做事做人如何。但是就这个 issue 而言，至少在这件事上，我觉得你这个人在这件事上很不厚道

说一句实话，作为一个开源社区的组成一部分，issue 里的抱怨和吐槽都无所谓，这本身就是社区的一部分，我觉得下面这样一些所谓不太友善的 issue，也比你这个 issue 体面的多

https://github.com/alibaba/AliSQL/issues/111

https://github.com/alibaba/AliSQL/issues/102

https://github.com/alibaba/AliSQL/issues/100

不管是阿里被人诟病的 KPI 式开源，还是这个 issue 里夹带着自己商业推广的行为，其实都是一回事，本质上都是对于社区生态的破坏。阿里的开源声望当年是怎么样被反噬的，作为这个 issue 的创建者，您也会怎么样被反噬，我相信这点您也应该有所体会了

but anyway, 还是祝您和您的项目能在开源社区里存活很久吧，来自中国的社区项目不多，大家也别互相斗了

以及 cc @xpchild 建议 lock 这个 issue，避免继续传播扩大了

**Comment by liukun4515** [comment]
> 非常遗憾，自从2018年5月之后，AliSQL就再也没有维护过开源版本了，嘛，这也无可厚非，开不开源是人家自己的决定，不过，中国MySQL开源生态的大旗，还是得有人得扛起来。
> 
> 我们现在做了一款基于MySQL内核的HTAP数据库，对标Heatwave架构，未来会支持分布式、云原生等架构，欢迎对数据库感兴趣的朋友们一起来共建：https://github.com/stoneatom/stonedb
> 
> 我们是完完全全、彻彻底底的长期开源，目前架构设计文档已经在Github上公布，欢迎大家了解~

@OpenDataBase 为什么在 https://github.com/stoneatom/stonedb/graphs/contributors 下没看到你的贡献?

感觉这是一个反向PR。
