### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by gimee88** [alibaba/AliSQL#13]
CMake Error at storage/tokudb/CMakeLists.txt:16 (MESSAGE):
  Building TokuDB ERROR, please check cmake>=2.8.9 and x86-64

-- Configuring incomplete, errors occurred!
See also "/home/mysql/AliSQL-master/CMakeFiles/CMakeOutput.log".
See also "/home/mysql/AliSQL-master/CMakeFiles/CMakeError.log".

**Comment by gimee88** [comment]
[root@cdit-0000908d AliSQL-master]# cmake -version
cmake version 2.8.12.2

**Comment by fungo** [comment]
检查下 gcc 版本，TokuDB 编译要求 gcc >= 4.7

**Comment by opdba** [comment]
-- Performing Test TOKUDB_OK
-- Performing Test TOKUDB_OK - Failed
CMake Error at storage/tokudb/CMakeLists.txt:16 (MESSAGE):
  Building TokuDB ERROR, please check cmake>=2.8.9 and x86-64


-- Configuring incomplete, errors occurred!
See also "/root/AliSQL-AliSQL-5.6.32-1/CMakeFiles/CMakeOutput.log".
See also "/root/AliSQL-AliSQL-5.6.32-1/CMakeFiles/CMakeError.log".
[root@xngpsegment01 AliSQL-AliSQL-5.6.32-1]# cmake
cmake
[root@xngpsegment01 AliSQL-AliSQL-5.6.32-1]# cmake --version
cmake version 2.8.12.2
[root@xngpsegment01 AliSQL-AliSQL-5.6.32-1]# gcc --version
gcc (GCC) 4.8.2
Copyright © 2013 Free Software Foundation, Inc.
本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
包括没有适销性和某一专用目的下的适用性担保

**Comment by opdba** [comment]
make，又报如下错：
Linking CXX static library libinnobase.a
[ 38%] Built target innobase
Scanning dependencies of target tokuportability_static_conv
[ 38%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/huge_page_detection.cc.o
[ 38%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/file.cc.o
[ 38%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/memory.cc.o
[ 38%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/os_malloc.cc.o
[ 38%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/portability.cc.o
[ 39%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/toku_assert.cc.o
[ 39%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/toku_crash.cc.o
[ 39%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/toku_path.cc.o
[ 39%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/toku_pthread.cc.o
[ 39%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/toku_time.cc.o
Linking CXX static library libtokuportability_static_conv.a
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ar terminated with signal 11 [Segmentation fault], core dumped
make[2]: *** [storage/tokudb/ft-index/portability/libtokuportability_static_conv.a] 错误 1
make[1]: *** [storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/all] 错误 2
make: *** [all] 错误 2
