### ISSUE TITLE
有没有Docker镜像？

### ISSUE THREAD

**Issue by caosm** [alibaba/AliSQL#14]
请问有没有AliSQL的官方Dockerfile？

**Comment by mokecc** [comment]
同样需要

**Comment by candyfairy** [comment]
在调试中哦

**Comment by fungo** [comment]
目前提供了一个测试版的 docker 镜像，使用方法如下：

```bash
$ docker pull registry.cn-hangzhou.aliyuncs.com/aliyun_console/alisql-inner:5.6.32
$ docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=hello1234 -d registry.cn-hangzhou.aliyuncs.com/aliyun_console/alisql-inner:5.6.32 mysqld
```

在宿主机上可以  `mysql -h127.0.0.1 -P3306 -uroot -phello1234` 来连数据库使用，数据目录是放在 `/opt/alisql/data` 下。

目前这个版本是不支持 TokuDB 的，因为 TokuDB 引擎需要禁用宿主系统的Transparent HugePages(`echo never > /sys/kernel/mm/transparent_hugepage/enabled`)，有的用户可能没有操作宿主系统配置的权限。随便会提供一个支持 TokuDB 的镜像。

这个 image 是供大家测试使用的，欢迎提改进意见 :-)

**Comment by fungo** [comment]
```bash
docker pull registry.cn-hangzhou.aliyuncs.com/acs-sample/alisql:latest
docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=hello1234 -d registry.cn-hangzhou.aliyuncs.com/acs-sample/alisql:latest mysqld
```
这是稳定版 docker image，用法和官方 mysql docker image 一样。

image 详细介绍请参考：[在容器中使用AliSQL](https://yq.aliyun.com/articles/62516)，可以自己本地使用，也可以通过阿里云的容器服务使用。

**Comment by flyer5200** [comment]
提个问题, registry.cn-hangzhou.aliyuncs.com/acs-sample/alisql:latest 这个镜像打的有问题, 镜像体积居然有2.4G, 我下载了运行起来进去容器看下目录结构, 发现/home目录下面有AliSQL的源码文件夹, 体积大概1.5G, 这个应该在编译出mysqld文件就清理掉的

**Comment by tekintian** [comment]
alisql的 Dockerfile 文件那里有?

**Comment by fungo** [comment]
@flyer5200 @tekintian 

可以试下新的镜像，压缩后不到100M

```
docker pull alisql/alisql
docker run --name some-alisql -e MYSQL_ROOT_PASSWORD=123456 -d -P alisql/alisql
```

详细信息在:  https://hub.docker.com/r/alisql/alisql/
