### ISSUE TITLE
各应用场景下的配置问题

### ISSUE THREAD

**Issue by daixh302** [alibaba/AliSQL#15]
对于不同的应用场景，如电商业务和金融业务，有没有区别优化的配置？还是说按照官方贴出的不同机型的标准配置，就以上两种场景都适合？

**Comment by tbdingqi** [comment]
这里给的几个cnf只是我们比较典型的配置，但是针对具体业务，建议您根据需求调整部分参数。比如，即使同一个库，在不同的时候，也会有不同的配置的，比较难遍历所有情况。
