### ISSUE TITLE
有没有相关文档

### ISSUE THREAD

**Issue by liaomars** [alibaba/AliSQL#19]
建议官方给个使用文档，现在都不知道怎么用

**Comment by tbdingqi** [comment]
您好，请见 https://github.com/alibaba/AliSQL  页面下方的两个Release Notes
https://github.com/alibaba/AliSQL/wiki/Changes-in-AliSQL-5.6.32-(2016-10-14)

**Comment by chenyu9390** [comment]
看了下，也没有发现是怎么去安装的。。另外为什么要是英语呢,

**Comment by tbdingqi** [comment]
@chenyu9390 这个文档也面向海外工程师，所以使用英文。都是比较简单的英文。
