### ISSUE TITLE
查阅AliSQL代码的时候，发现thread_handing只有三个选项值，不包含thread_pool，是不支持线程池了么？

### ISSUE THREAD

**Issue by jaredzhu** [alibaba/AliSQL#20]
static Sys_var_enum Sys_thread_handling(
       "thread_handling",
       "Define threads usage for handling queries, one of "
       **"one-thread-per-connection, no-threads, loaded-dynamically"**
       , READ_ONLY GLOBAL_VAR(thread_handling), CMD_LINE(REQUIRED_ARG),
       thread_handling_names, DEFAULT(0));

**Comment by jaredzhu** [comment]
https://bugs.mysql.com/bug.php?id=69000

**Comment by jaredzhu** [comment]
static Sys_var_enum Sys_thread_handling(
       "thread_handling",
       "Define threads usage for handling queries, one of "
       "one-thread-per-connection, no-threads"
#ifdef HAVE_POOL_OF_THREADS
       ", **pool-of-threads**"
#endif
       , READ_ONLY GLOBAL_VAR(thread_handling), CMD_LINE(REQUIRED_ARG),
       thread_handling_names,
       DEFAULT(DEFAULT_THREAD_HANDLING)
 );
这个是percona的代码，pool-of-threads 特性在AliSQL是不支持么？或者是用什么方式替代了？

**Comment by tbdingqi** [comment]
AliSQL是基于Oracle 版本的，Oracle版本默认没有线程池，我们会在后续将内部实现的版本开源出来。
