### ISSUE TITLE
有没有相关的安装和使用文档

### ISSUE THREAD

**Issue by chenyu9390** [alibaba/AliSQL#21]
https://github.com/alibaba/AliSQL/wiki/Changes-in-AliSQL-5.6.32-(2016-09-15)
https://github.com/alibaba/AliSQL/wiki/Changes-in-AliSQL-5.6.32-(2016-10-14)
从这2个网址中只看到了如何去使用,对如何安装还是有点模糊

**Comment by tbdingqi** [comment]
安装就是使用MySQL通用的安装命令即可，这个与官方一致

**Comment by fungo** [comment]
请参考 MySQL 官方的源码安装指导： [Installing MySQL Using a Development Source Tree](https://dev.mysql.com/doc/refman/5.6/en/installing-development-tree.html)

**Comment by Loongle** [comment]
没有windows版本？搞鸡毛了?

**Comment by tbdingqi** [comment]
@Loongle  有源码可以直接编译的。不过由于我们自己没有windows的生产环境，因此不建议您将AliSQL直接用在windows生产环境中

**Comment by lslxdx** [comment]
@chenyu9390 亲测 @fungo 大神的安装教程好使！
我结合自己安装过程中遇到的一些问题, 整理了一些`启动`, `关闭`和`Disabling Transparent Hugepages for TokuDB`相关的操作(http://www.lslxdx.com/2017/03/02/alisql%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91/)，希望可以有点帮助。
