### ISSUE TITLE
MySQL-Transfer的PATCH有打进去吗？

### ISSUE THREAD

**Issue by sansom** [alibaba/AliSQL#23]
MySQL-Transfer的PATCH有打进去吗？此版本是否支持多线程复制？

**Comment by tbdingqi** [comment]
有多线程复制功能就不需要打transfer的patch了。目前开源的版本中还只是直接支持官方的多线程复制(基于库）。

**Comment by sansom** [comment]
丁爷你MySQL-Transfer没有支持5.6吗？跪求啊

**Comment by tbdingqi** [comment]
@sansom 这个按步骤是要先把基于表和事务的并行复制加进来，再加入transfer的功能。
