### ISSUE TITLE
make编译出错

### ISSUE THREAD

**Issue by opdba** [alibaba/AliSQL#25]
make，又报如下错：
Linking CXX static library libinnobase.a
[ 38%] Built target innobase
Scanning dependencies of target tokuportability_static_conv
[ 38%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/huge_page_detection.cc.o
[ 38%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/file.cc.o
[ 38%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/memory.cc.o
[ 38%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/os_malloc.cc.o
[ 38%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/portability.cc.o
[ 39%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/toku_assert.cc.o
[ 39%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/toku_crash.cc.o
[ 39%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/toku_path.cc.o
[ 39%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/toku_pthread.cc.o
[ 39%] Building CXX object storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/toku_time.cc.o
Linking CXX static library libtokuportability_static_conv.a
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/ar terminated with signal 11 [Segmentation fault], core dumped
make[2]: **\* [storage/tokudb/ft-index/portability/libtokuportability_static_conv.a] 错误 1
make[1]: **\* [storage/tokudb/ft-index/portability/CMakeFiles/tokuportability_static_conv.dir/all] 错误 2
make: **\* [all] 错误 2

**Comment by opdba** [comment]
[100%] Built target sql_embedded
[100%] Built target mysqlserver
Linking CXX executable mysql_client_test_embedded
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::estimate_rows_upper_bound()’中：
ha_tokudb.cc:(.text+0x321)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::rnd_end()’中：
ha_tokudb.cc:(.text+0x3bb)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x401)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::scan_time() [clone .localalias.205]’中：
ha_tokudb.cc:(.text+0x496)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x4f1)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0x57b): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::~ha_tokudb()’中：
ha_tokudb.cc:(.text+0x858)：对‘toku_dbt_array_destroy’未定义的引用
ha_tokudb.cc:(.text+0x878)：对‘toku_dbt_array_destroy’未定义的引用
ha_tokudb.cc:(.text+0x889)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x8d1)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘tokudb_release_savepoint(handlerton*, THD*, void*)’中：
ha_tokudb.cc:(.text+0x9af)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x9f9)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xa41)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0xce9): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘show_tokudb_ha_vars(THD*, st_mysql_show_var*, char*)’中：
ha_tokudb.cc:(.text+0x174c)：对‘read_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0x175f)：对‘read_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0x1772)：对‘read_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0x1785)：对‘read_partitioned_counter’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘tokudb_xa_prepare(handlerton*, THD*, bool)’中：
ha_tokudb.cc:(.text+0x18b9)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x196f)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x19b1)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x19f1)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x1a51)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0x214b): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘tokudb_show_engine_status(THD*, bool (*)(THD*, char const*, unsigned int, char const*, unsigned int, char const*, unsigned int)) [clone .constprop.217]’中：
ha_tokudb.cc:(.text+0x234e)：对‘read_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0x2524)：对‘read_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0x255c)：对‘tokutime_to_seconds(unsigned long)’未定义的引用
ha_tokudb.cc:(.text+0x26c8)：对‘read_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0x2704)：对‘read_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0x2740)：对‘read_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0x2783)：对‘read_partitioned_counter’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::bas_ext() const’中：
ha_tokudb.cc:(.text+0x2aed)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::read_time(unsigned int, unsigned int, unsigned long long)’中：
ha_tokudb.cc:(.text+0x394d)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x39b1)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x3a51)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x3b21)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0x4f42): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::ha_tokudb(handlerton*, TABLE_SHARE*)’中：
ha_tokudb.cc:(.text+0x50fd)：对‘toku_dbt_array_init’未定义的引用
ha_tokudb.cc:(.text+0x511d)：对‘toku_dbt_array_init’未定义的引用
ha_tokudb.cc:(.text+0x540b)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::read_full_row(unsigned char*)’中：
ha_tokudb.cc:(.text+0x55bb)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x5608)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x5621)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::get_pos(__toku_dbt*, unsigned char*)’中：
ha_tokudb.cc:(.text+0x56fa)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0x579a): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘tokudb::create_status(__toku_db_env*, __toku_db**, char const*, __toku_db_txn*)’中：
ha_tokudb.cc:(.text+0x79ac)：对‘db_create’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘tokudb::open_status(__toku_db_env*, __toku_db**, char const*, __toku_db_txn*)’中：
ha_tokudb.cc:(.text+0x7a8c)：对‘db_create’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘tokudb_done_func(void*)’中：
ha_tokudb.cc:(.text+0x823f)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x8281)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::index_flags(unsigned int, unsigned int, bool) const’中：
ha_tokudb.cc:(.text+0x83e1)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘open_status_dictionary(__toku_db**, char const*, __toku_db_txn*)’中：
ha_tokudb.cc:(.text+0x8509)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::open_main_dictionary(char const*, bool, __toku_db_txn*)’中：
ha_tokudb.cc:(.text+0x861b)：对‘db_create’未定义的引用
ha_tokudb.cc:(.text+0x8779)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘tokudb_discover2(handlerton*, THD*, char const*, char const*, bool, unsigned char**, unsigned long*) [clone .constprop.218]’中：
ha_tokudb.cc:(.text+0x8adf)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x8b4b)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x8bd1)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x8c81)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0x8e96): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::__close()’中：
ha_tokudb.cc:(.text+0x9df0)：对‘toku_dbt_array_destroy’未定义的引用
ha_tokudb.cc:(.text+0x9e10)：对‘toku_dbt_array_destroy’未定义的引用
ha_tokudb.cc:(.text+0x9e65)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x9eac)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x9eec)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::close()’中：
ha_tokudb.cc:(.text+0x9f6f)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x9fb1)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0xa199): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::index_first(unsigned char*)’中：
ha_tokudb.cc:(.text+0xc2f0)：对‘increment_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0xc317)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xc371)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::index_last(unsigned char*)’中：
ha_tokudb.cc:(.text+0xc501)：对‘increment_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0xc528)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xc581)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::info(unsigned int)’中：
ha_tokudb.cc:(.text+0xc6d6)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xc741)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xc799)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0xc8a1): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘create_sub_table(char const*, __toku_dbt*, __toku_db_txn*, unsigned int, unsigned int, toku_compression_method, bool)’中：
ha_tokudb.cc:(.text+0xd4e2)：对‘db_create’未定义的引用
ha_tokudb.cc:(.text+0xd52e)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xd621)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::prepare_inplace_alter_table(TABLE*, Alter_inplace_info*)’中：
ha_tokudb.cc:(.text+0xde09)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘show_tokudb_vars(THD*, st_mysql_show_var*, char*)’中：
ha_tokudb.cc:(.text+0xe16a)：对‘read_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0xe1fa)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xe24a)：对‘tokutime_to_seconds(unsigned long)’未定义的引用
ha_tokudb.cc:(.text+0xe361)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘tokudb_init_func(void*)’中：
ha_tokudb.cc:(.text+0xe407)：对‘create_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0xe413)：对‘create_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0xe41f)：对‘create_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0xe42b)：对‘create_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0xe4df)：对‘db_env_set_toku_product_name’未定义的引用
ha_tokudb.cc:(.text+0xe698)：对‘db_env_create’未定义的引用
ha_tokudb.cc:(.text+0xe88c)：对‘db_env_set_direct_io’未定义的引用
ha_tokudb.cc:(.text+0xe949)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xe99d)：对‘toku_os_get_phys_memory_size()’未定义的引用
ha_tokudb.cc:(.text+0xe9b0)：对‘toku_os_get_max_process_data_size(unsigned long*)’未定义的引用
ha_tokudb.cc:(.text+0xe9f1)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xeb3b)：对‘create_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0xebcc)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xec2b)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xec6c)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xecba)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘tokudb_flush_logs(handlerton*, unsigned long long)’中：
ha_tokudb.cc:(.text+0xeea9)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0xef61): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘tokudb_end(handlerton*, ha_panic_function)’中：
ha_tokudb.cc:(.text+0xf18f)：对‘destroy_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0xf1ab)：对‘destroy_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0xf1bc)：对‘destroy_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0xf1cd)：对‘destroy_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0xf1de)：对‘destroy_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0xf229)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xf279)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xf306)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘tokudb_xa_recover(handlerton*, xid_t*, unsigned int)’中：
ha_tokudb.cc:(.text+0xf499)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0xf4b9)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0xf4f1): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘tokudb_fractal_tree_block_map_fill_table(THD*, TABLE_LIST*, Item*)’中：
ha_tokudb.cc:(.text+0x11151)：对‘db_create’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘tokudb_fractal_tree_info_fill_table(THD*, TABLE_LIST*, Item*)’中：
ha_tokudb.cc:(.text+0x1199b)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x11a84)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x11b31)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x11bb1)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x11ccb)：对‘db_create’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::open_secondary_dictionary(__toku_db**, st_key*, char const*, bool, __toku_db_txn*)’中：
ha_tokudb.cc:(.text+0x155b7)：对‘db_create’未定义的引用
ha_tokudb.cc:(.text+0x156b7)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::commit_inplace_alter_table(TABLE*, Alter_inplace_info*, bool)’中：
ha_tokudb.cc:(.text+0x1599f)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x15b90)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::delete_or_rename_table(char const*, char const*, bool)’中：
ha_tokudb.cc:(.text+0x17402)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x17611)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0x17671): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::get_next(unsigned char*, int, __toku_dbt*, bool)’中：
ha_tokudb.cc:(.text+0x1deee)：对‘increment_partitioned_counter’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::index_next(unsigned char*)’中：
ha_tokudb.cc:(.text+0x1e146)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x1e191)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::index_prev(unsigned char*)’中：
ha_tokudb.cc:(.text+0x1e236)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x1e281)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::rnd_next(unsigned char*)’中：
ha_tokudb.cc:(.text+0x1e31d)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0x1e361): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::delete_row(unsigned char const*)’中：
ha_tokudb.cc:(.text+0x1ec41)：对‘increment_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0x1ec59)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x1ed02)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::create_dbt_key_for_lookup(__toku_dbt*, st_key*, unsigned char*, unsigned char const*, bool*, int)’中：
ha_tokudb.cc:(.text+0x1ed8d)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::end_bulk_insert(bool)’中：
ha_tokudb.cc:(.text+0x1f592)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x1f701)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0x1fe19): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::update_row(unsigned char const*, unsigned char*)’中：
ha_tokudb.cc:(.text+0x21581)：对‘increment_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0x215c1)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x21621)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::write_row(unsigned char*)’中：
ha_tokudb.cc:(.text+0x21b4e)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x21d29)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x21e5b)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x21f2c)：对‘increment_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0x220d1)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x22131)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x22199)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::create(char const*, TABLE*, st_ha_create_information*)’中：
ha_tokudb.cc:(.text+0x2298a)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x22a1d)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0x22b28): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::index_read(unsigned char*, unsigned char const*, unsigned int, ha_rkey_function)’中：
ha_tokudb.cc:(.text+0x25f08)：对‘increment_partitioned_counter’未定义的引用
ha_tokudb.cc:(.text+0x25f30)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x26281)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x262d9)：对‘toku_os_gettid()’未定义的引用
ha_tokudb.cc:(.text+0x26331)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o)：在函数‘ha_tokudb::index_next_same(unsigned char*, unsigned char const*, unsigned int)’中：
ha_tokudb.cc:(.text+0x264cf)：对‘toku_os_gettid()’未定义的引用
../libmysqld.a(ha_tokudb.cc.o):ha_tokudb.cc:(.text+0x265b1): more undefined references to `toku_os_gettid()' follow
../libmysqld.a(ha_tokudb.cc.o)：在函数‘toku_hton_update_primary_key_bytes_inserted(unsigned long)’中：
ha_tokudb.cc:(.text+0x78db)：对‘increment_partitioned_counter’未定义的引用
collect2: error: ld returned 1 exit status
make[2]: *** [libmysqld/examples/mysql_client_test_embedded] 错误 1
make[1]: *** [libmysqld/examples/CMakeFiles/mysql_client_test_embedded.dir/all] 错误 2
make: *** [all] 错误 2




大写的服！！！！！make 100%抛出这个错误。。。。。。。。。。。。。。。。

**Comment by fungo** [comment]
先通过添加 cmake 参数

`-DWITH_EMBEDDED_SERVER=0`  // 禁用 embedded server

或者

`-DWITH_TOKUDB_STORAGE_ENGINE=0`  // 禁用 TokuDB

来绕过。
