### ISSUE TITLE
tokudb编译错误

### ISSUE THREAD

**Issue by zhoubofsy** [alibaba/AliSQL#26]
alisql编译过程中增加tokudb，编译器使用的4.7.4，cmake用的2.8.12，ld版本2.25，系统是rhel6.4。
编译报错：
[ 29%] Built target tokuportability_static
[ 29%] Building CXX object storage/tokudb/ft-index/ft/CMakeFiles/logformat.dir/logger/logformat.cc.o
Linking CXX executable logformat
c++: error: -fuse-linker-plugin is not supported in this configuration
make[2]: *** [storage/tokudb/ft-index/ft/logformat] Error 1
make[1]: *** [storage/tokudb/ft-index/ft/CMakeFiles/logformat.dir/all] Error 2
make: *** [all] Error 2

**Comment by fungo** [comment]
建议升级下 gcc 版本再试下，可以参考下这里：[AliSQL 源码编译](http://blog.fungo.me/2016/10/compile-alisql-from-source/)。

**Comment by handi901107** [comment]
请问 和mariadb相比   性能如何

**Comment by zhoubofsy** [comment]
@fungo 按你给的网址试了一下，现在能编译过了，必须用devtoolset-4，devtoolset-3都不行（报ar段错误）。谢谢！
