### ISSUE TITLE
大神们 这个怎么处理

### ISSUE THREAD

**Issue by xiaoqiang2209** [alibaba/AliSQL#31]
[ 45%] Building CXX object storage/innobase/CMakeFiles/innobase.dir/row/row0ins.cc.o
[ 45%] Building CXX object storage/innobase/CMakeFiles/innobase.dir/row/row0merge.cc.o
[ 45%] Building CXX object storage/innobase/CMakeFiles/innobase.dir/row/row0mysql.cc.o
/home/qiangchen4/AliSQL-master/storage/innobase/row/row0mysql.cc:69:19: error: zutil.h: No such file or directory
/home/qiangchen4/AliSQL-master/storage/innobase/row/row0mysql.cc: In function ‘unsigned char* row_compress_column(const unsigned char*, ulint*, ulint, row_prebuilt_t*)’:
/home/qiangchen4/AliSQL-master/storage/innobase/row/row0mysql.cc:358: error: ‘DEF_MEM_LEVEL’ was not declared in this scope
make[2]: *** [storage/innobase/CMakeFiles/innobase.dir/row/row0mysql.cc.o] Error 1
make[1]: *** [storage/innobase/CMakeFiles/innobase.dir/all] Error 2

**Comment by xiaomiwujiecao** [comment]
你是make的时候出错的吧 检查一下 相关的依赖库

**Comment by xiaoqiang2209** [comment]
cp zlib/* storage/innobase/row/ 
竟然make 通过了....
