### ISSUE TITLE
支持json 格式这类数据吗？json模糊查询性能如何？

### ISSUE THREAD

**Issue by lqixv** [alibaba/AliSQL#34]
MongoDB的json的模糊查询听说性能比较差，alisql 怎么样？

**Comment by fungo** [comment]
AliSQL 没有对 JSON 做特殊支持，和官方 MySQL 5.6 行为一样。

**Comment by lqixv** [comment]
我印象中，MySQL 5.7 才支持 json 格式的数据

**Comment by zhaoshiling1017** [comment]
是的，5.7版本开始支持json数据类型和相关函数。

**Comment by zjsxfly** [comment]
alisql什么时候支持mysql 5.7版的json类型
