### ISSUE TITLE
cmake tokudb报错

### ISSUE THREAD

**Issue by smoothjump** [alibaba/AliSQL#38]
### cmake命令
      cmake . \
      -DCMAKE_INSTALL_PREFIX=/database/mysql3007 \
      -DMYSQL_TCP_PORT=3007 \
      -DMYSQL_DATADIR=/database/mysql3007/data \
      -DSYSCONFDIR=/etc \
      -DWITH_INNOBASE_STORAGE_ENGINE=1 \
      -DWITH_PARTITION_STORAGE_ENGINE=1 \
      -DWITH_FEDERATED_STORAGE_ENGINE=1 \
      -DWITH_BLACKHOLE_STORAGE_ENGINE=1 \
      -DWITH_TOKUDB_STORAGE_ENGINE=1 \
      -DWITH_MYISAM_STORAGE_ENGINE=1 \
      -DMYSQL_UNIX_ADDR=/tmp/mysql.sock \
      -DWITH_EMBEDDED_SERVER=0 \
      -DENABLE_DTRACE=0 \
      -DENABLED_LOCAL_INFILE=1 \
      -DDEFAULT_CHARSET=utf8mb4 \
      -DDEFAULT_COLLATION=utf8mb4_general_ci \
      -DCMAKE_EXE_LINKER_FLAGS="-ljemalloc" \
      -DWITH_SAFEMALLOC=OFF \
      -DEXTRA_CHARSETS=all
执行以上cmake命令出错，在Performing Test TOKUDB_OK步骤失败
错误日志：

	Run Build Command:/usr/bin/gmake "cmTryCompileExec1917338609/fast"
	/usr/bin/gmake -f CMakeFiles/cmTryCompileExec1917338609.dir/build.make CMakeFiles/cmTryCompileExec1917338609.dir/build
	gmake[1]: Entering directory `/root/AliSQL-master/CMakeFiles/CMakeTmp'
	/usr/bin/cmake -E cmake_progress_report /root/AliSQL-master/CMakeFiles/CMakeTmp/CMakeFiles 1
	Building CXX object CMakeFiles/cmTryCompileExec1917338609.dir/src.cxx.o
	/usr/bin/c++   -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGE_FILES -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Wall -Wextra -Wformat-security -Wvla -Woverloaded-virtual -Wno-unused-parameter -DTOKUDB_OK   -o CMakeFiles/cmTryCompileExec1917338609.dir/src.cxx.o -c /root/AliSQL-master/CMakeFiles/CMakeTmp/src.cxx
	/root/AliSQL-master/CMakeFiles/CMakeTmp/src.cxx:3: 错误：expected primary-expression before ‘.’ token
	/root/AliSQL-master/CMakeFiles/CMakeTmp/src.cxx:3: 错误：expected primary-expression before ‘.’ token
	gmake[1]: Leaving directory `/root/AliSQL-master/CMakeFiles/CMakeTmp'
	gmake[1]: *** [CMakeFiles/cmTryCompileExec1917338609.dir/src.cxx.o] 错误 1
	gmake: *** [cmTryCompileExec1917338609/fast] 错误 2

	Source file was:

	struct a {int b; int c; };
	struct a d = { .b=1, .c=2 };
	int main() { return 0; }

# uname -a
Linux iZ1hj9esnmZ 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

cmake 版本2.8.12.2

**Comment by fungo** [comment]
检查下gcc版本，要求 `gcc >= 4.7`，可以参考下 [AliSQL 源码编译](http://blog.fungo.me/2016/10/compile-alisql-from-source/) 。
