### ISSUE TITLE
make 编译出错 In file included from /root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:18:0: /root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.h:87:18: 错误：‘Master_info’未声明

### ISSUE THREAD

**Issue by thefuyang** [alibaba/AliSQL#39]
[ 93%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/__/sql/procedure.cc.o
[ 93%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/__/sql/protocol.cc.o
[ 93%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/__/sql/records.cc.o
[ 93%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/__/sql/rpl_handler.cc.o
[ 93%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/__/sql/scheduler.cc.o
[ 93%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/__/sql/set_var.cc.o
[ 93%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/__/sql/signal_handler.cc.o
[ 93%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/__/sql/semisync.cc.o
[ 93%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/__/sql/semisync_master.cc.o
[ 93%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/__/sql/semisync_slave.cc.o
In file included from /root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:18:0:
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.h:87:18: 错误：‘Master_info’未声明
 int slaveReply(Master_info* mi);
                  ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.h:88:18: 错误：‘Master_info’未声明
 int slaveStart(Master_info *mi);
                  ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.h:89:17: 错误：‘Master_info’未声明
 int slaveStop(Master_info *mi);
                 ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.h:90:23: 错误：‘Master_info’未声明
 int requestTransmit(Master_info*);
                       ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.h:92:18: 错误：‘Master_info’未声明
 int resetSlave(Master_info *mi);
                  ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:85:35: 错误：‘int ReplSemiSyncSlave::slaveStart’不是‘class ReplSemiSyncSlav ’的静态成员                                                                                                                       int ReplSemiSyncSlave::slaveStart(Master_info *mi)
                                   ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:85:35: 错误：‘Master_info’在此作用域中尚未声明
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:85:48: 错误：‘mi’在此作用域中尚未声明
int ReplSemiSyncSlave::slaveStart(Master_info *mi)
                                                ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:86:1: 错误：expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:104:34: 错误：‘int ReplSemiSyncSlave::slaveStop’不是‘class ReplSemiSyncSlav ’的静态成员                                                                                                                       int ReplSemiSyncSlave::slaveStop(Master_info *mi)
                                  ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:104:34: 错误：‘Master_info’在此作用域中尚未声明
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:104:47: 错误：‘mi’在此作用域中尚未声明
int ReplSemiSyncSlave::slaveStop(Master_info *mi)
                                               ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:105:1: 错误：expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:113:35: 错误：‘int ReplSemiSyncSlave::resetSlave’不是‘class ReplSemiSyncSlav  ve’的静态成员
 int ReplSemiSyncSlave::resetSlave(Master_info *mi)
                                   ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:113:35: 错误：‘Master_info’在此作用域中尚未声明
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:113:48: 错误：‘mi’在此作用域中尚未声明
 int ReplSemiSyncSlave::resetSlave(Master_info *mi)
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:114:1: 错误：expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:147:40: 错误：‘int ReplSemiSyncSlave::requestTransmit’不是‘class ReplSemiSyn  ncSlave’的静态成员
 int ReplSemiSyncSlave::requestTransmit(Master_info *mi)
                                        ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:147:40: 错误：‘Master_info’在此作用域中尚未声明
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:147:53: 错误：‘mi’在此作用域中尚未声明
 int ReplSemiSyncSlave::requestTransmit(Master_info *mi)
                                                     ^
/root/AliSQL-AliSQL-5.6.32-4/sql/semisync_slave.cc:148:1: 错误：expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
make[2]: *** [libmysqld/CMakeFiles/sql_embedded.dir/__/sql/semisync_slave.cc.o] 错误 1
make[1]: *** [libmysqld/CMakeFiles/sql_embedded.dir/all] 错误 2
make: *** [all] 错误 2

centos 7 
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

**Comment by fungo** [comment]
@thefuyang  cmake 参数是怎样的？

**Comment by thefuyang** [comment]
不好意思，确实是CMAKE参数的问题。
根据这个http://blog.fungo.me/2016/10/compile-alisql-from-source/ 里面配置cmake参数就对了
