### ISSUE TITLE
ERROR! The server quit without updating PID file

### ISSUE THREAD

**Issue by jay763190097** [alibaba/AliSQL#43]
Starting MySQL.... ERROR! The server quit without updating PID file (/usr/local/mysql/data/centos6.5.pid).
试了几种方法都不成功

**Comment by fungo** [comment]
麻烦提供下启动方式（具体的命令），和更多的错误信息上下文。

**Comment by liqingrikeiikyeong** [comment]
[root@libohan-node alisql]# cd support-files/
[root@libohan-node support-files]# ll
total 32
-rwxr-xr-x. 1 root root  1153 Mar 14 08:30 binary-configure
-rw-r--r--. 1 root root   773 Mar 14 08:28 magic
-rw-r--r--. 1 root root  1126 Mar 14 08:30 my-default.cnf
-rwxr-xr-x. 1 root root  1061 Mar 14 08:30 mysqld_multi.server
-rwxr-xr-x. 1 root root   869 Mar 14 08:30 mysql-log-rotate
-rwxr-xr-x. 1 root root 10850 Mar 14 08:30 mysql.server
[root@libohan-node support-files]# ./mysql.server start
Starting MySQL. ERROR! The server quit without updating PID file (/var/lib/mysql/libohan-node.pid).
[root@libohan-node support-files]# ps -ef | grep mysql
root     41426 13366  0 09:01 pts/0    00:00:00 grep --color=auto mysql
[root@libohan-node support-files]# cat /var/lib/mysql/libohan-node.pid
cat: /var/lib/mysql/libohan-node.pid: No such file or directory

**Comment by fungo** [comment]
这个是 mysql 的初始化和启动问题，参考下官方文档 [Postinstallation Setup and Testing](https://dev.mysql.com/doc/refman/5.6/en/postinstallation.html)。

**Comment by jay763190097** [comment]
已经安装成功了，之前是看的这个教程[Alisql源码编译安装](http://www.2cto.com/database/201612/576878.html)，但是他这命令好像用户没有创建成功，授权什么的不好弄。
