### ISSUE TITLE
编译出错？semisync_slave.h:87:18: error: ?.aster_info?.has not been declared

### ISSUE THREAD

**Issue by lwcloud** [alibaba/AliSQL#45]
In file included from /root/Downloads/AliSQL-master/sql/semisync_slave.cc:18:0:
/root/Downloads/AliSQL-master/sql/semisync_slave.h:87:18: error: ?.aster_info?.has not been declared
   int slaveReply(Master_info* mi);
                  ^
/root/Downloads/AliSQL-master/sql/semisync_slave.h:88:18: error: ?.aster_info?.has not been declared
   int slaveStart(Master_info *mi);
                  ^
/root/Downloads/AliSQL-master/sql/semisync_slave.h:89:17: error: ?.aster_info?.has not been declared
   int slaveStop(Master_info *mi);
                 ^
/root/Downloads/AliSQL-master/sql/semisync_slave.h:90:23: error: ?.aster_info?.has not been declared
   int requestTransmit(Master_info*);
                       ^
/root/Downloads/AliSQL-master/sql/semisync_slave.h:92:18: error: ?.aster_info?.has not been declared
   int resetSlave(Master_info *mi);
                  ^
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:85:35: error: ?.nt ReplSemiSyncSlave::slaveStart?.is not a static data member of ?.lass ReplSemiSyncSlave?
 int ReplSemiSyncSlave::slaveStart(Master_info *mi)
                                   ^
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:85:35: error: ?.aster_info?.was not declared in this scope
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:85:48: error: ?.i?.was not declared in this scope
 int ReplSemiSyncSlave::slaveStart(Master_info *mi)
                                                ^
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:86:1: error: expected ?.?.or ?.?.before ?.?.token
 {
 ^
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:104:34: error: ?.nt ReplSemiSyncSlave::slaveStop?.is not a static data member of ?.lass ReplSemiSyncSlave?
 int ReplSemiSyncSlave::slaveStop(Master_info *mi)
                                  ^
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:104:34: error: ?.aster_info?.was not declared in this scope
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:104:47: error: ?.i?.was not declared in this scope
 int ReplSemiSyncSlave::slaveStop(Master_info *mi)
                                               ^
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:105:1: error: expected ?.?.or ?.?.before ?.?.token
 {
 ^
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:113:35: error: ?.nt ReplSemiSyncSlave::resetSlave?.is not a static data member of ?.lass ReplSemiSyncSlave?
 int ReplSemiSyncSlave::resetSlave(Master_info *mi)
                                   ^
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:113:35: error: ?.aster_info?.was not declared in this scope
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:113:48: error: ?.i?.was not declared in this scope
 int ReplSemiSyncSlave::resetSlave(Master_info *mi)
                                                ^
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:114:1: error: expected ?.?.or ?.?.before ?.?.token
 {
 ^
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:147:40: error: ?.nt ReplSemiSyncSlave::requestTransmit?.is not a static data member of ?.lass ReplSemiSyncSlav?
 int ReplSemiSyncSlave::requestTransmit(Master_info *mi)
                                        ^
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:147:40: error: ?.aster_info?.was not declared in this scope
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:147:53: error: ?.i?.was not declared in this scope
 int ReplSemiSyncSlave::requestTransmit(Master_info *mi)
                                                     ^
/root/Downloads/AliSQL-master/sql/semisync_slave.cc:148:1: error: expected ?.?.or ?.?.before ?.?.token
 {
 ^
make[2]: *** [libmysqld/CMakeFiles/sql_embedded.dir/__/sql/semisync_slave.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libmysqld/CMakeFiles/sql_embedded.dir/all] Error 2
make: *** [all] Error 2

**Comment by fungo** [comment]
请参考编译指导 [alisql-compiler-guide](https://github.com/alibaba/AliSQL#alisql-compiler-guide)。
