### ISSUE TITLE
还是编译出错No install step for 'jemalloc'

### ISSUE THREAD

**Issue by lwcloud** [alibaba/AliSQL#46]
Linking C static library libstrings.a
[ 14%] Built target strings
[ 15%] No install step for 'jemalloc'
[ 15%] Completed 'jemalloc'
[ 15%] Built target jemalloc
make: *** [all] Error 2

**Comment by lslxdx** [comment]
我在多次cmake的时候也遇到了。删掉项目，重新解压+cmake，一切正常。

**Comment by fungo** [comment]
请参考编译指导 [alisql-compiler-guide](https://github.com/alibaba/AliSQL#alisql-compiler-guide)。
