### ISSUE TITLE
开源alisql对于热点行更新没有提升？

### ISSUE THREAD

**Issue by Aresxiao** [alibaba/AliSQL#49]
我做了一个alisql秒杀场景的压测，这是我的压测报告(http://blog.csdn.net/joshly/article/details/61930353  )，感觉开源的alisql在热点行更新上并没有提升。

**Comment by Aresxiao** [comment]
不知道是否我有哪个地方有问题。

**Comment by fungo** [comment]
参考下我们的测试报告：[AliSQL Performance benchmark for inventory](https://github.com/alibaba/AliSQL/wiki/AliSQL-Performance-benchmark-for-inventory)，是不是没有设置参数 `set global rds_ic_reduce_hint_enable=ON`？

**Comment by Aresxiao** [comment]
嗯，多谢，我试试看。
