### ISSUE TITLE
alisql/sql/semisync_slave.h:88:18: 错误：‘Master_info’未声明

### ISSUE THREAD

**Issue by yyyyyyy9** [alibaba/AliSQL#50]
1、
gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/gcc-6.3.0/libexec/gcc/x86_64-pc-linux-gnu/6.3.0/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：./configure --prefix=/usr/local/gcc-6.3.0/ -enable-threads=posix --disable-checking --disable-multilib --enable-languages=c,c++ --with-gmp=/usr/local/gmp-6.1.0/ --with-mpfr=/usr/local/mpfr-3.1.4/ --with-mpc=/usr/local/mpc-1.0.3/
线程模型：posix
gcc 版本 6.3.0 (GCC) 

2、
home/OOOO/alisql/sql/semisync_slave.h:88:18: 错误：‘Master_info’未声明
   int slaveReply(Master_info* mi);
                  ^~~~~~~~~~~

**Comment by fungo** [comment]
应该是 cmake 参数不对，参考下这个issue: https://github.com/alibaba/AliSQL/issues/39

**Comment by yyyyyyy9** [comment]
3Q
