### ISSUE TITLE
alisql 一直编译不过 求解

### ISSUE THREAD

**Issue by hanbinpro** [alibaba/AliSQL#55]
系统centos 

cmake的日志一直是：

/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec744034495.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileExec744034495.dir/CheckFunctionExists.c.o  -o cmTryCompileExec744034495 -rdynamic -lpthreads 
/opt/rh/devtoolset-4/root/usr/bin/ld: cannot find -lpthreads
collect2: ld returned 1 exit status
gmake[1]: Leaving directory `/root/AliSQL/CMakeFiles/CMakeTmp'
gmake[1]: *** [cmTryCompileExec744034495] Error 1
gmake: *** [cmTryCompileExec744034495/fast] Error 2

**Comment by ivmm** [comment]
GCC啥版本？

**Comment by hanbinpro** [comment]
用的是devtoolset-4 gcc5.3
