### ISSUE TITLE
ubuntu 16.10 编译报错

### ISSUE THREAD

**Issue by sidealice** [alibaba/AliSQL#56]
In file included from /root/AliSQL/storage/tokudb/ft-index/util/dmt.h:731:0,
                 from /root/AliSQL/storage/tokudb/ft-index/ft/bndata.h:93,
                 from /root/AliSQL/storage/tokudb/ft-index/ft/bndata.cc:92:
/root/AliSQL/storage/tokudb/ft-index/ft/bndata.cc: In function ‘toku::dmt<klpair_struct, klpair_struct*, toku::klpair_dmtwriter>::copyout(unsigned int*, klpair_struct**, unsigned int, klpair_struct*)’:
/root/AliSQL/storage/tokudb/ft-index/util/dmt.cc:955:5: error: nonnull argument ‘outlen’ compared to NULL [-Werror=nonnull-compare]
     if (outlen) {
     ^~
/root/AliSQL/storage/tokudb/ft-index/util/dmt.cc:958:5: error: nonnull argument ‘out’ compared to NULL [-Werror=nonnull-compare]
     if (out) {
     ^~

是不是tokudb的部分，我需要有额外库引入？

**Comment by xpchild** [comment]
Hi, 这里我们有准备一篇专门的文章介绍 编译的， http://blog.fungo.me/2016/10/compile-alisql-from-source/   
供参考。
