### ISSUE TITLE
Ubuntu 14.04 Compile error

### ISSUE THREAD

**Issue by nshigit** [alibaba/AliSQL#60]
OS: Ubuntu 14.04 3.16.0-52-generic x86_64
gcc/g++: Ubuntu 4.8.4-2ubunutu1~14.04.3

--------------------------------------------
[ 87%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/__/sql/semisync_slave.cc.o
In file included from /home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:18:0:
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.h:87:18: error: ‘Master_info’ has not been declared
   int slaveReply(Master_info* mi);
                  ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.h:88:18: error: ‘Master_info’ has not been declared
   int slaveStart(Master_info *mi);
                  ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.h:89:17: error: ‘Master_info’ has not been declared
   int slaveStop(Master_info *mi);
                 ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.h:90:23: error: ‘Master_info’ has not been declared
   int requestTransmit(Master_info*);
                       ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.h:92:18: error: ‘Master_info’ has not been declared
   int resetSlave(Master_info *mi);
                  ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:85:35: error: ‘int ReplSemiSyncSlave::slaveStart’ is not a static member of ‘class ReplSemiSyncSlave’
 int ReplSemiSyncSlave::slaveStart(Master_info *mi)
                                   ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:85:35: error: ‘Master_info’ was not declared in this scope
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:85:48: error: ‘mi’ was not declared in this scope
 int ReplSemiSyncSlave::slaveStart(Master_info *mi)
                                                ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:86:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:104:34: error: ‘int ReplSemiSyncSlave::slaveStop’ is not a static member of ‘class ReplSemiSyncSlave’
 int ReplSemiSyncSlave::slaveStop(Master_info *mi)
                                  ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:104:34: error: ‘Master_info’ was not declared in this scope
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:104:47: error: ‘mi’ was not declared in this scope
 int ReplSemiSyncSlave::slaveStop(Master_info *mi)
                                               ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:105:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:113:35: error: ‘int ReplSemiSyncSlave::resetSlave’ is not a static member of ‘class ReplSemiSyncSlave’
 int ReplSemiSyncSlave::resetSlave(Master_info *mi)
                                   ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:113:35: error: ‘Master_info’ was not declared in this scope
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:113:48: error: ‘mi’ was not declared in this scope
 int ReplSemiSyncSlave::resetSlave(Master_info *mi)
                                                ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:114:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:147:40: error: ‘int ReplSemiSyncSlave::requestTransmit’ is not a static member of ‘class ReplSemiSyncSlave’
 int ReplSemiSyncSlave::requestTransmit(Master_info *mi)
                                        ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:147:40: error: ‘Master_info’ was not declared in this scope
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:147:53: error: ‘mi’ was not declared in this scope
 int ReplSemiSyncSlave::requestTransmit(Master_info *mi)
                                                     ^
/home/nshi/workspace/AliSQL-5.6.32-5/sql/semisync_slave.cc:148:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
make[2]: *** [libmysqld/CMakeFiles/sql_embedded.dir/__/sql/semisync_slave.cc.o] Error 1
make[1]: *** [libmysqld/CMakeFiles/sql_embedded.dir/all] Error 2
make: *** [all] Error 2

**Comment by xpchild** [comment]
Hi， 参考一下这篇文章，http://blog.fungo.me/2016/10/compile-alisql-from-source/

**Comment by xpchild** [comment]
或者请更新最新代码。
