### ISSUE TITLE
开源的alisql是否支持select from update这样的 语法

### ISSUE THREAD

**Issue by yiwenshuo** [alibaba/AliSQL#61]
我在我的阿里云RDS mysql 上运行 ：
SELECT id2 FROM UPDATE t1 SET id2 = id2 + 1
WHERE
	id1 = 1;
是可以执行成功的。

但是我本机将最新版本的alisql 编译安装好以后，运行同样的SQL,报错：
root@localhost : ywsdb 18:27:17> SELECT id2 FROM UPDATE t1 SET id2 = id2 + 1
    -> WHERE
    -> id1 = 1;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UPDATE t1 SET id2 = id2 + 1
WHERE
id1 = 1' at line 1

请问是否是开源版本的AliSQL将select from update这个功能语法给阉割了？

**Comment by xpchild** [comment]
我们即将在新的版本中开源这个功能，敬请期待。
