### ISSUE TITLE
centOS 编译错误

### ISSUE THREAD

**Issue by zivy009** [alibaba/AliSQL#63]
/mnt/service/AliSQL/sql/sql_planner.cc:431:18: note: ‘loose_scan_opt.Loose_scan_opt::best_loose_scan_start_key’ was declared here
   Loose_scan_opt loose_scan_opt;

**Comment by zivy009** [comment]
按文档：https://www.mf8.biz/install-alisql-with-tokudb/  报错 

  [ 17%] Built target regex
make: *** [all] Error 2

**Comment by ivmm** [comment]
系统是不是 CentOS 6？ 推荐使用 CentOS 7 编译

**Comment by zivy009** [comment]
也是 CentOS 7  它，新装的。 阿里云新买的服器器。

**Comment by xpchild** [comment]
拉最新的代码再编译一下。
