### ISSUE TITLE
2017年7月20下午约2点拉的代码，编译出错

### ISSUE THREAD

**Issue by daixh302** [alibaba/AliSQL#65]
[ 93%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/__/sql/semisync_master.cc.o
[ 93%] Building CXX object libmysqld/CMakeFiles/sql_embedded.dir/__/sql/semisync_slave.cc.o
In file included from /root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:18:0:
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.h:87:18: error: ‘Master_info’ has not been declared
   int slaveReply(Master_info* mi);
                  ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.h:88:18: error: ‘Master_info’ has not been declared
   int slaveStart(Master_info *mi);
                  ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.h:89:17: error: ‘Master_info’ has not been declared
   int slaveStop(Master_info *mi);
                 ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.h:90:23: error: ‘Master_info’ has not been declared
   int requestTransmit(Master_info*);
                       ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.h:92:18: error: ‘Master_info’ has not been declared
   int resetSlave(Master_info *mi);
                  ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:85:35: error: ‘int ReplSemiSyncSlave::slaveStart’ is not a static member of ‘class ReplSemiSyncSlave’
 int ReplSemiSyncSlave::slaveStart(Master_info *mi)
                                   ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:85:35: error: ‘Master_info’ was not declared in this scope
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:85:48: error: ‘mi’ was not declared in this scope
 int ReplSemiSyncSlave::slaveStart(Master_info *mi)
                                                ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:86:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:104:34: error: ‘int ReplSemiSyncSlave::slaveStop’ is not a static member of ‘class ReplSemiSyncSlave’
 int ReplSemiSyncSlave::slaveStop(Master_info *mi)
                                  ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:104:34: error: ‘Master_info’ was not declared in this scope
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:104:47: error: ‘mi’ was not declared in this scope
 int ReplSemiSyncSlave::slaveStop(Master_info *mi)
                                               ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:105:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:113:35: error: ‘int ReplSemiSyncSlave::resetSlave’ is not a static member of ‘class ReplSemiSyncSlave’
 int ReplSemiSyncSlave::resetSlave(Master_info *mi)
                                   ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:113:35: error: ‘Master_info’ was not declared in this scope
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:113:48: error: ‘mi’ was not declared in this scope
 int ReplSemiSyncSlave::resetSlave(Master_info *mi)
                                                ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:114:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:147:40: error: ‘int ReplSemiSyncSlave::requestTransmit’ is not a static member of ‘class ReplSemiSyncSlave’
 int ReplSemiSyncSlave::requestTransmit(Master_info *mi)
                                        ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:147:40: error: ‘Master_info’ was not declared in this scope
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:147:53: error: ‘mi’ was not declared in this scope
 int ReplSemiSyncSlave::requestTransmit(Master_info *mi)
                                                     ^
/root/lnmp20170720/src/alisql5.6.32/sql/semisync_slave.cc:148:1: error: expected ‘,’ or ‘;’ before ‘{’ token
 {
 ^
make[2]: *** [libmysqld/CMakeFiles/sql_embedded.dir/__/sql/semisync_slave.cc.o] Error 1
make[1]: *** [libmysqld/CMakeFiles/sql_embedded.dir/all] Error 2
make: *** [all] Error 2

**Comment by xpchild** [comment]
参考下： http://blog.fungo.me/2016/10/compile-alisql-from-source/

**Comment by Annyudie** [comment]
相同报错 centos7.3

**Comment by eurekaka** [comment]
相同的错误，按照链接做了之后还是有错，gcc-c++版本5.3.1，cmake版本2.8.12，我的编译类型是Debug，不知道是不是原因

**Comment by xpchild** [comment]
cmake 配置参数请参考：cmake .                              \
 -DCMAKE_BUILD_TYPE="Release"         \
 -DCMAKE_INSTALL_PREFIX="/opt/alisql" \
 -DWITH_EMBEDDED_SERVER=0             \
 -DWITH_EXTRA_CHARSETS=all            \
 -DWITH_MYISAM_STORAGE_ENGINE=1       \
 -DWITH_INNOBASE_STORAGE_ENGINE=1     \
 -DWITH_PARTITION_STORAGE_ENGINE=1    \
 -DWITH_CSV_STORAGE_ENGINE=1          \
 -DWITH_ARCHIVE_STORAGE_ENGINE=1      \
 -DWITH_BLACKHOLE_STORAGE_ENGINE=1    \
 -DWITH_FEDERATED_STORAGE_ENGINE=1    \
 -DWITH_PERFSCHEMA_STORAGE_ENGINE=1   \
 -DWITH_TOKUDB_STORAGE_ENGINE=1

**Comment by xpchild** [comment]
最新的代码已经修复此问题，请更新下。
