### ISSUE TITLE
2017-07-16最后的版本没有semisync模块了

### ISSUE THREAD

**Issue by boonie81** [alibaba/AliSQL#66]
AliSQL不再支持semisync模块了吗，plugin目录下没有了，编译也没有semisync_master.so和semisync_slave.so这两个文件。

**Comment by xpchild** [comment]
AliSQL静态编译了semisync，性能比动态链接库的方式有所提升。

**Comment by boonie81** [comment]
怎么使用呢，在做主备的时候，不需要install 插件了吗？

**Comment by xpchild** [comment]
不需要install，可以直接使用

**Comment by boonie81** [comment]
好的，谢谢了

**Comment by boonie81** [comment]
遇到一个问题，在使用after_sync后，主机宕机后，最后一条数据再主机重启启动时，会写入到数据库中，而在主机宕机后，我把从机已经设置为新主机，这个问题如何解决？ 下面是涉及的semi相关的值。
+---------------------------------------+------------+
| Variable_name                         | Value      |
+---------------------------------------+------------+
| rpl_semi_sync_master_enabled          | ON         |
| rpl_semi_sync_master_timeout          | 60000      |
| rpl_semi_sync_master_trace_level      | 32         |
| rpl_semi_sync_master_wait_no_slave    | ON         |
| rpl_semi_sync_master_wait_point       | after_sync |
| rpl_semi_sync_slave_delay_master      | ON         |
| rpl_semi_sync_slave_enabled           | OFF        |
| rpl_semi_sync_slave_kill_conn_timeout | 5          |
| rpl_semi_sync_slave_trace_level       | 32         |
+---------------------------------------+------------+

**Comment by boonie81** [comment]
两台mysql的数据不一致了，不是说after_sync之后，就可以解决这个问题了吗？

**Comment by xpchild** [comment]
after_sync并不是用来解决这个极端情况下的数据不一致问题，而是用来解决可见性问题。
你说的这种场景，semisync本身是无法完成数据一致性的，需要额外工具或者机制来辅助完成，比如原主库重建，或者flashback掉prepared的transaction等。
