### ISSUE TITLE
编译在这个地方老是报错，试过了好几遍

### ISSUE THREAD

**Issue by DarkiT** [alibaba/AliSQL#8]
[ 99%] Building C object libmysqld/CMakeFiles/mysqlserver.dir/mysqlserver_depends.c.o 
Linking C static library libmysqld.a 
/bin/ar: creating /tmp/mysql-alisql-5.6.32/libmysqld/libmysqld.a 
[ 99%] Built target mysqlserver 
Scanning dependencies of target mysql_client_test_embedded 
[100%] Building C object libmysqld/examples/CMakeFiles/mysql_client_test_embedded.dir/__/__/tests/mysql_client_test.c.o 
Linking CXX executable mysql_client_test_embedded 
../libmysqld.a(lib_sql.cc.o): In function `clean_up': 

/tmp/mysql-alisql-5.6.32/libmysqld/../sql/mysqld.cc:1930: undefined reference to `free_global_table_stats()' 

/tmp/mysql-alisql-5.6.32/libmysqld/../sql/mysqld.cc:1931: undefined reference to `free_global_index_stats()' 

../libmysqld.a(lib_sql.cc.o): In function `init_server_components': 

/tmp/mysql-alisql-5.6.32/libmysqld/../sql/mysqld.cc:4745: undefined reference to `init_global_table_stats()' 

/tmp/mysql-alisql-5.6.32/libmysqld/../sql/mysqld.cc:4746: undefined reference to `init_global_index_stats()' 

collect2: error: ld returned 1 exit status 
make[2]: *** [libmysqld/examples/mysql_client_test_embedded] Error 1 
make[1]: *** [libmysqld/examples/CMakeFiles/mysql_client_test_embedded.dir/all] Error 2 
make: *** [all] Error 2

**Comment by xpchild** [comment]
RDS环境没有编译embedded server，导致patch在预编译EMBEDDED_LIBRARY的处理上存在缺陷，master已修复，请更新重试，给你带来的不变，请多包涵，欢迎继续使用，并提宝贵意见。

**Comment by DarkiT** [comment]
自己已经修改了源代码，程序已经编译成功！正在测试！
