### ISSUE TITLE
The e-mail address of the AliSQL code owner?

### ISSUE THREAD

**Issue by movie-travel-code** [alibaba/AliSQL#80]
Hi,
I'm WangLiushuai from 360 CodeSafe Team. We found some weaknesses/bugs in AliSQL using our static analysis tools and I want to send the more detailed information to the code owner.

I don't know whether it is appropriate here to ask this question. If it is not suitable, please forgive me. E-mail address can be sent to `wangliushuai@360.net` or `movietravelcode@outlook.com`.

Thank you!
360 CodeSafe

**Comment by xpchild** [comment]
Hi, WangLiushuai
Just put it here as you will,  or send it to jianwei.zhao@alibaba-inc.com.
Look forward to the detailed information.

**Comment by movie-travel-code** [comment]
@xpchild Hi xpchild, thank you for your information.  Sorry for my delayed reply. I have sent the analysis results about AliSQL to  `jianwei`.
